version: '3'
services:
  node_api:
    build: .
    environment:
      - PORT=1337
      - ENV_IN=docker
    ports:
      - "1337:1337"
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
    restart: always